---

- hosts: all
  vars:
    http_proxy: "http://wwwproxy.sandia.gov:80"
    https_proxy: "http://wwwproxy.sandia.gov:80"
  gather_facts: True

  tasks:
    - name: upgrade all Ubuntu packages
      apt:
        name: '*'
        state: latest
